[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash*" = "Clash"

[icons]
Edge = "ïŠ‚"
Thunar = "ï¼"
kitty = "ï’‰"
KeePassXC = "ï‚„"
obsidian = "ó°º¿"
wps = "îš¥"
Code = "îº§"
Clash = "ó°²€"
Zotero = "î®œ"
okular = "ï‡"
Zeal = "ïˆ"

[general]
default_icon = "ï„‘"
split_at = ":"
empty_label = "ğŸŒ•"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
