[icons]
"Microsoft-edge" = "ï‰¨"
Thunar = "ï¼"
kitty = "ï„ "
KeePassXC = "ï‚„"
obsidian = "ï€­"
wps = "ó±”˜"
code-oss = "ï„¡"

[general]
default_icon = "ï„‘"
split_at = ":"
empty_label = "ğŸŒ•"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
