[aliases.class]
"Microsoft-edge" = "Edge"
"zen-browser" = "Zen"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"
"firefox*" = "Firefox"
"dev.zed.Zed" = "Zed"
"dev.warp.Warp" = "Warp"
"strawberry" = "Music"
"com.github.johnfactotum.Foliate" = "Reader"
"libreoffice-writer" = "Writer"
"libreoffice-calc" = "Excel"
"libreoffice-impress" = "Slides"
"libreoffice-startcenter" = "Office"
"jetbrains-studio" = "Android Studio"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"
"MATLAB.*" = "Matlab"
"Wolfram.*" = "Mathematica"

[icons]
Edge = "ïŠ‚"
Chromium = "ï‰¨"
Firefox = "ï‰©"
Zen = "ï‰©"
Thunar = "ï¼"
Kitty = "î•"
Wezterm = "î•"
Warp = "î•"
XPipe = "î•"
KeePassXC = "ï‚„"
obsidian = "ó°º¿"
Word = "ó°ˆ­"
Excel = "ó°ˆœ"
Slides = "ó°ˆ¨"
Office = "ó°ˆ­"
Cursor = "ó°…¨"
Code = "ó°…¨"
Zed = "ó°…¨"
Clash = "ó°²€"
Zotero = "î®œ"
okular = "ó°ˆ¦"
Zeal = "ïˆ"
DingTalk = "ï‰º"
Matlab = "ï†ª"
Mathematica = "ï†ª"
wechat = "ï‡—"
Music = "ï€"
Reader = "îª¤"
"LM Studio" = "î¸"
CherryStudio = "îŠ›"
"Android Studio" = "ó°€²"

[general]
separator = " î‚± "
split_at = ":"
empty_label = "ğŸ†“"
display_property = "instance"
default_icon = "ï„‘"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
