[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"

[icons]
Edge = "ïŠ‚"
Thunar = "ï¼"
Kitty = "ï’‰"
Wezterm = "ï’‰"
KeePassXC = "ï‚„"
obsidian = "ó°º¿"
Word = "îš¥"
Excel = "îš¦"
Slides = "ï‡„"
Code = "îº§"
Clash = "ó°²€"
Zotero = "î®œ"
okular = "ï‡"
Zeal = "ïˆ"
DingTalk = "ï‰º"

[general]
default_icon = "ï„‘"
split_at = ":"
empty_label = "ğŸŒ•"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
