[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"
"dev.warp.Warp" = "Warp"
"firefox*" = "Firefox"
"dev.zed.Zed" = "Zed"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"
"MATLAB.*" = "Matlab"
"Wolfram.*" = "Mathematica"

[icons]
Edge = "ïŠ‚"
Firefox = "ï‰©"
Thunar = "ï¼"
Kitty = "ï’‰"
Wezterm = "ï’‰"
Warp = "ï’‰"
KeePassXC = "ï‚„"
obsidian = "ó°º¿"
Word = "îš¥"
Excel = "îš¦"
Slides = "ï‡„"
Code = "îº§"
Zed = "îº§"
Clash = "ó°²€"
Zotero = "î®œ"
okular = "ï‡"
Zeal = "ïˆ"
DingTalk = "ï‰º"
Matlab = "ï†ª"
Mathematica = "ï†ª"
wechat = "ï‡—"

[general]
default_icon = "ï„‘"
split_at = ":"
empty_label = "ğŸŒ•"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
